-- =====Creating a table
DROP TABLE TOAD_USER.CUSTOMERS CASCADE CONSTRAINTS;
CREATE TABLE TOAD_USER.CUSTOMERS
(
  ID           NUMBER                           NOT NULL,
  NAME         VARCHAR2(200 BYTE)               NOT NULL,
  DESCRIPTION  VARCHAR2(1000 BYTE),
  USERNAME     VARCHAR2(200 BYTE)
)

--- ======Creating a sequence
DROP SEQUENCE TOAD_USER.CUSTOMER_SEQ;
CREATE SEQUENCE TOAD_USER.CUSTOMER_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

