DECLARE
  CURSOR EMPLOYEE_CURSOR IS
     SELECT EMPLOYEE_ID, SALARY, COMMISSION_PCT, COUNT(START_DATE) JOBCOUNT
     FROM EMPLOYEES LEFT OUTER JOIN JOB_HISTORY JH
     USING(EMPLOYEE_ID)
     GROUP BY EMPLOYEE_ID,SALARY,COMMISSION_PCT
     ORDER BY 1;
   V_BONUS NUMBER(5);
BEGIN
  FOR  EMPLOYEE_RECORD IN EMPLOYEE_CURSOR
  LOOP
     IF EMPLOYEE_RECORD.JOBCOUNT > 0 THEN
        V_BONUS := EMPLOYEE_RECORD.SALARY * 0.40;
     ELSIF EMPLOYEE_RECORD.COMMISSION_PCT IS NOT NULL THEN
        V_BONUS := EMPLOYEE_RECORD.SALARY * 0.25;
     ELSE
        V_BONUS := EMPLOYEE_RECORD.SALARY * 0.35;
     END IF;
     
     DBMS_OUTPUT.PUT_LINE(EMPLOYEE_RECORD.EMPLOYEE_ID || ' - ' || V_BONUS);
  END LOOP;     
END;
