----===================== SCRIPT TO CREATE EMPLOYEES TABLE =================
CREATE TABLE RAJ.EMPLOYEES
(
  EMPLOYEE_ID     NUMBER(6),
  FIRST_NAME      VARCHAR2(20 BYTE),
  LAST_NAME       VARCHAR2(25 BYTE) NOT NULL,
  EMAIL           VARCHAR2(25 BYTE) NOT NULL,
  PHONE_NUMBER    VARCHAR2(20 BYTE),
  HIRE_DATE       DATE NOT NULL,
  JOB_ID          VARCHAR2(10 BYTE)NOT NULL,
  SALARY          NUMBER(8,2),
  COMMISSION_PCT  NUMBER(2,2),
  MANAGER_ID      NUMBER(6),
  DEPARTMENT_ID   NUMBER(4)
);


----===================== SCRIPT TO CREATE HISTORY TABLE =================
CREATE TABLE RAJ.JOB_HISTORY
(
  EMPLOYEE_ID    NUMBER(6)  NOT NULL,
  START_DATE     DATE NOT NULL,
  END_DATE       DATE  NOT NULL,
  JOB_ID         VARCHAR2(10 BYTE) NOT NULL,
  DEPARTMENT_ID  NUMBER(4)
)